version: "3"

volumes:
  node_modules:

services:
  api:
    command: sh -c "yarn install && yarn watch"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 4000:4000
      - 9229:9229